[project]
name = "mimo"
version = "0.1.0"
description = "Diffusion and score-based MIMO channel estimation"
readme = "README.md"
requires-python = "~=3.13.0"

dependencies = []

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
